### ISSUE TITLE
Pass parameters to Actionname?

### ISSUE THREAD

**Issue by webkluns** [elrod/php-easyMVC#1]
Is it possible to pass parameters to a Actionname?
Would be great to be able to call it like:
http://index.php?rt=controllerName/actionName/parameterValue

**Comment by elrod** [comment]
You cannot pass a parameter this way in the current release, i labeled your request as an enhacement for the next release, anyway as a workaround, you can still pass your parameters via $_GET or $_POST, for instance a call like: 
http://index.php?rt=controllerName/actionName&parametername=parametervalue, would do the job, you will find your parametervalue in $_GET['parametername'];
